const last_personal_info = {
  marshrut: "",
  marshrut_cordinant: "",
  transfer_type: "one_way",
  pickup_date: "",
  pickup_time: "",
  total_distance: "",
  total_time: "",
  passenger: "",
  bag: "",
  standart: "",
  vehicle: {},
  vehicle_id: null,
  type: "",
  name: "",
  surname: "",
  email: "",
  phone: "",
  message: "",
  bus: "",
  total_amount: 0,
};

let times = [
  "0:00",
  "0:30",
  "1:00",
  "1:30",
  "2:00",
  "2:30",
  "3:00",
  "3:30",
  "4:00",
  "4:30",
  "5:00",
  "5:30",
  "6:00",
  "6:30",
  "7:00",
  "7:30",
  "8:00",
  "8:30",
  "9:00",
  "9:30",
  "10:00",
  "10:30",
  "11:00",
  "11:30",
  "12:00",
  "12:30",
  "13:00",
  "13:30",
  "14:00",
  "14:30",
  "15:00",
  "15:30",
  "16:00",
  "16:30",
  "17:00",
  "17:30",
  "18:00",
  "18:30",
  "19:00",
  "19:30",
  "20:00",
  "20:30",
  "21:00",
  "21:30",
  "22:00",
  "22:30",
  "22:00",
  "23:30",
  "23:00",
  "24:00",
  "24:30",
];

const cars = [
  {
    vehicle_id: 1,
    img: "assets/img/vito.jpg",
    vehicle_name: "Vito",
    vehicle_type: "Minivan",
    price: 35,
  },
  {
    vehicle_id: 2,
    img: "assets/img/vito.jpg",
    vehicle_name: "Vito",
    vehicle_type: "Minivan",
    price: 25,
  },
  {
    vehicle_id: 3,
    img: "assets/img/vito.jpg",
    vehicle_name: "Vito",
    vehicle_type: "Minivan",
    price: 90,
  },
  {
    vehicle_id: 4,
    img: "assets/img/vito.jpg",
    vehicle_name: "Vito",
    vehicle_type: "Minivan",
    price: 40,
  },
  {
    vehicle_id: 5,
    img: "assets/img/vito.jpg",
    vehicle_name: "Vito",
    vehicle_type: "Minivan",
    price: 20,
  },
  {
    vehicle_id: 6,
    img: "assets/img/vito.jpg",
    vehicle_name: "Vito",
    vehicle_type: "Minivan",
    price: 15,
  },
  {
    vehicle_id: 7,
    img: "assets/img/vito.jpg",
    vehicle_name: "Vito",
    vehicle_type: "Minivan",
    price: 20,
  },
];
const tours = [
  {
    tour_id: 1,
    img: "assets/img/agdam.jpg",
    tour_name: "Agdam",
    tour_type: "Econom",
    price: 135,
  },
  {
    tour_id: 2,
    img: "assets/img/lenkeran.jfif",
    tour_name: "Lenkeran",
    tour_type: "Econom",
    price: 135,
  },
  {
    tour_id: 3,
    img: "assets/img/qebele.jpg",
    tour_name: "Qebele",
    tour_type: "Econom",
    price: 135,
  },
  {
    tour_id: 4,
    img: "assets/img/agdam.jpg",
    tour_name: "Agdam",
    tour_type: "Econom",
    price: 135,
  },
  {
    tour_id: 5,
    img: "assets/img/lenkeran.jfif",
    tour_name: "Lenkeran",
    tour_type: "Econom",
    price: 135,
  },
  {
    tour_id: 6,
    img: "assets/img/qebele.jpg",
    tour_name: "Qebele",
    tour_type: "Econom",
    price: 135,
  },
];
