const translations = {
  az: {
    home: "Əsas səhifə",
    about: "Haqqımızda",
    services: "Xidmətlərimiz",
    gallery: "Qalereya",
    tours: "Turlar",
    contact: "Əlaqə",
    language_az: "AZ",
    language_ru: "RU",
    language_en: "EN",
    currency_azn: "AZN",
    currency_usd: "USD",
    currency_eur: "EUR",
    slide1_title: "Sizin Yerli Transfer Xidmətiniz — Rahat və Güvənli Səyahətə Başlayın!",
    slide1_description:
      "Sizin Yerli Transfer Xidmətiniz — Rahat və Güvənli Səyahətə Başlayın! LocalTransfer.com ilə şəhərdaxili və hava limanı transferlərinizi asanlıqla planlaşdırın. Təcrübəli sürücülər və rahat avtomobillər ilə səyahətiniz hər zaman təhlükəsiz və komfortlu olacaq. Birbaşa sifariş",
    slide2_title: "Sizin Yerli Transfer Xidmətiniz — Rahat və Güvənli Səyahətə Başlayın!",
    slide2_description:
      "Sizin Yerli Transfer Xidmətiniz — Rahat və Güvənli Səyahətə Başlayın! LocalTransfer.com ilə şəhərdaxili və hava limanı transferlərinizi asanlıqla planlaşdırın. Təcrübəli sürücülər və rahat avtomobillər ilə səyahətiniz hər zaman təhlükəsiz və komfortlu olacaq. Birbaşa sifariş",
    slide3_title: "Sizin Yerli Transfer Xidmətiniz — Rahat və Güvənli Səyahətə Başlayın!",
    slide3_description:
      "Sizin Yerli Transfer Xidmətiniz — Rahat və Güvənli Səyahətə Başlayın! LocalTransfer.com ilə şəhərdaxili və hava limanı transferlərinizi asanlıqla planlaşdırın. Təcrübəli sürücülər və rahat avtomobillər ilə səyahətiniz hər zaman təhlükəsiz və komfortlu olacaq. Birbaşa sifariş",
    step1_label: "Sürüş detallarını daxil edin",
    step2_label: "Avtomobil seçin",
    step3_label: "Əlaqə məlumatlarını daxil edin",
    step4_label: "Sifariş detallarına bax",
    ride_details_title: "SÜRÜŞ DETALLARI",
    pickup_date_label: "Götürmə tarixi",
    pickup_time_label: "Götürmə vaxtı",
    route_label: "Marşrut",
    select_route: "Marşrutu seçin",
    route_naxcivan: "Naxçıvan",
    route_lenkeran: "Lənkəran",
    route_sirvan: "Şirvan",
    route_qebele: "Qəbələ",
    route_agdam: "Ağdam",
    route_masalli: "Masallı",
    transfer_type_label: "Transfer tipi",
    one_way_option: "Bir istiqamət",
    total_distance_label: "Ümumi məsafə",
    total_time_label: "Ümumi vaxt",
    total_label: "Ümumi",
    vehicle_filter_title: "AVTOMOBİL FİLTERİ",
    passenger_label: "Sərnişinlər",
    bag_label: "Çamadanlar",
    standard_label: "Standart",
    type_label: "Standart",
    select_option: "Seçin",
    all_vehicles: "Bütün avtomobillər",
    minivan: "Mini van",
    contact_info_title: "Əlaqə məlumatları",
    name_label: "Ad",
    surname_label: "Soyad",
    email_label: "E-mail ünvanı",
    phone_label: "Telefon",
    order_note_label: "Sifariş üçün əlavə qeydlər",
    ride_details: "Sürüş detalları",
    order_title: "Sifariş",
    payment_method_label: "Ödəniş üsulu:",
    payment_method_value: "Çatdırılma zamanı nəğd ödəniş",
    privacy_note:
      "Sizin şəxsi məlumatlarınız sifarişinizi emal etmək, bu veb-saytda təcrübənizi dəstəkləmək və məxfilik siyasətimizdə təsvir olunan digər məqsədlər üçün istifadə olunacaq",
    confirm_order_button: "Sifarişi təsdiqlə",
    step_0_button_next: "Avtomobili seçin <i class='fa-solid fa-chevron-right'></i>",
    step_1_button_prev: "<i class='fa-solid fa-chevron-left'></i> Sürüş detallarını seçin",
    step_1_button_next: "Əlaqə məlumatlarını daxil edin <i class='fa-solid fa-chevron-right'></i>",
    step_2_button_prev: "<i class='fa-solid fa-chevron-left'></i> Avtomobili seçin",
    step_2_button_next: "Sifariş detallatına baxın <i class='fa-solid fa-chevron-right'></i>",
    step_3_button_prev: "<i class='fa-solid fa-chevron-left'></i> Əlaqə məlumatlarını daxil edin",
    step_3_button_next: "İndi rezerv edin <i class='fa-solid fa-chevron-right'></i>",
    intro_heading:
      "LocalTransfer.com, rahat və etibarlı nəqliyyat həlləri təqdim edərək, istifadəçilərə səyahət prosesini asanlaşdırmaq məqsədilə qurulmuşdur.",
    intro_description:
      "Peşəkar sürücülərimiz və geniş avtomobil parkımızla yüksək keyfiyyətli xidmət və fərdiləşdirilmiş marşrutlar təklif edirik. Azərbaycanın gözəlliklərini kəşf etmək üçün bizimlə səyahət edin!",
    service_airport: "Hava Limanı Transferləri",
    service_vip: "VIP köçürmələr",
    service_rental: "Sürücü ilə avtomobil icarəsi",
    service_excursion: "İstəyinizə uyğun olaraq istənilən istiqamətə ekskursiyalar",
    service_tours: "Turlar",
    learn_more: "Ətraflı öyrən <i class='fa-solid fa-chevron-right'></i>",
    car_list_title: "Təklif etdiyimiz avtomobillərin siyahısı",
    partners_title: "Partnyorlarımız",
    service_coverage: "Xidmətlərimizi Azərbaycanın hər bir bölgəsində təqdim edirik.",
    comfort_reliability_title: "Rahatlıq və Etibar",
    comfort_reliability_text:
      "Xidmətlərimiz sayəsində səyahətiniz zamanı maksimum rahatlıq əldə edəcəksiniz. Avtomobilinizi asanlıqla bron edin və vaxtında təhvil alacağınıza əmin olun.",
    customer_satisfaction_title: "Müştəri Məmnuniyyəti",
    customer_satisfaction_text:
      "Nəqliyyat sahəsindəki zəngin təcrübəmiz sayəsində, çoxsaylı məmnun müştəri və tərəfdaşlara sahibik. Bu da, peşəkar və keyfiyyətli xidmətlərimizin etibarlılığının ən yaxşı göstəricisidir.",
    services_offered: "Sizə təklif edə biləcəyimiz xidmətlər",
    airport_transfer: "Hava Limanı transferi",
    find_on_map: "Bizi xəritədə tapın",
    why_us: "Niyə biz?",
    professional_drivers: "Peşəkar Sürücülər",
    professional_drivers_desc: "Sürücülərimizin hər biri peşəkarlığı və punktuallığı ilə seçilir",
    safety: "Təhlükəsizlik",
    safety_desc: "Müştərilərimizin təhlükəsizliyi bizim əsas prioritetimizdir",
    reliable_guidance: "Etibarlı Bələdçilik",
    reliable_guidance_desc: "Turunuzda sizə bələdçilik etmək üçün bilik və təcrübəmizə etibar edə bilərsiniz",
    premium_service: "Premium Xidmət",
    premium_service_desc: "Premium keyfiyyət və mükafat qazanan müştəri xidməti",
    videos: "Videolar",
    cars: "Maşınlar",
    address: "Ünvan",
    location: "Ünvan",
    location_all: "Hamısı",
    location_baku: "Bakı",
    location_ganja: "Gəncə",
    location_sumgait: "Sumqayıt",
    location_mingecevir: "Mingəçevir",
    location_lenkaran: "Lənkəran",
    location_shirvan: "Şirvan",
    location_gabala: "Qəbələ",
    location_agdam: "Ağdam",
    location_masalli: "Masallı",
    location_nakhchivan: "Naxçıvan",
    category: "Kateqoriya",
    category_all: "Hamısı",
    category_option1: "Kateqoriya 1",
    category_option2: "Kateqoriya 2",
  },
  en: {
    home: "Home",
    about: "About Us",
    services: "Our Services",
    gallery: "Gallery",
    tours: "Tours",
    contact: "Contact",
    language_az: "AZ",
    language_ru: "RU",
    language_en: "EN",
    currency_azn: "AZN",
    currency_usd: "USD",
    currency_eur: "EUR",
    slide1_title: "Your Local Transfer Service - Start a Comfortable and Safe Journey!",
    slide1_description:
      "Your Local Transfer Service - Start a Comfortable and Safe Journey! Plan your city and airport transfers easily with LocalTransfer.com. With experienced drivers and comfortable vehicles, your journey will always be safe and comfortable. Book directly",
    slide2_title: "Your Local Transfer Service - Start a Comfortable and Safe Journey!",
    slide2_description:
      "Your Local Transfer Service - Start a Comfortable and Safe Journey! Plan your city and airport transfers easily with LocalTransfer.com. With experienced drivers and comfortable vehicles, your journey will always be safe and comfortable. Book directly",
    slide3_title: "Your Local Transfer Service - Start a Comfortable and Safe Journey!",
    slide3_description:
      "Your Local Transfer Service - Start a Comfortable and Safe Journey! Plan your city and airport transfers easily with LocalTransfer.com. With experienced drivers and comfortable vehicles, your journey will always be safe and comfortable. Book directly",
    step1_label: "Enter ride details",
    step2_label: "Select vehicle",
    step3_label: "Enter contact information",
    step4_label: "Review order details",

    ride_details_title: "RIDE DETAILS",
    pickup_date_label: "Pickup Date",
    pickup_time_label: "Pickup Time",
    route_label: "Route",
    select_route: "Select a route",
    route_naxcivan: "Nakhchivan",
    route_lenkeran: "Lankaran",
    route_sirvan: "Shirvan",
    route_qebele: "Gabala",
    route_agdam: "Agdam",
    route_masalli: "Masalli",
    transfer_type_label: "Transfer Type",
    one_way_option: "One Way",
    total_distance_label: "Total Distance",
    total_time_label: "Total Time",
    total_label: "Total",
    vehicle_filter_title: "VEHICLE FILTER",
    passenger_label: "Passengers",
    bag_label: "Bags",
    standard_label: "Standard",
    type_label: "Type",
    select_option: "Select",
    all_vehicles: "All vehicles",
    minivan: "Mini van",
    contact_info_title: "Contact Information",
    name_label: "First Name",
    surname_label: "Last Name",
    email_label: "Email Address",
    phone_label: "Phone",
    order_note_label: "Additional Notes for Order",
    ride_details: "Ride Details",
    order_title: "Order",
    payment_method_label: "Payment Method:",
    payment_method_value: "Cash on delivery",
    privacy_note:
      "Your personal information will be used to process your order, support your experience throughout this website, and for other purposes described in our privacy policy.",
    confirm_order_button: "Confirm Order",
    step_0_button_next: "Select Vehicle <i class='fa-solid fa-chevron-right'></i>",
    step_1_button_prev: "<i class='fa-solid fa-chevron-left'></i> Select Ride Details",
    step_1_button_next: "Enter Contact Details <i class='fa-solid fa-chevron-right'></i>",
    step_2_button_prev: "<i class='fa-solid fa-chevron-left'></i> Select Vehicle",
    step_2_button_next: "View Order Details <i class='fa-solid fa-chevron-right'></i>",
    step_3_button_prev: "<i class='fa-solid fa-chevron-left'></i> Enter Contact Details",
    step_3_button_next: "Reserve Now <i class='fa-solid fa-chevron-right'></i>",
    intro_heading:
      "LocalTransfer.com was established to simplify the travel process by providing convenient and reliable transportation solutions.",
    intro_description:
      "With our professional drivers and large fleet, we offer high-quality service and personalized routes. Travel with us to discover the beauty of Azerbaijan!",
    service_airport: "Airport Transfers",
    service_vip: "VIP Transfers",
    service_rental: "Car Rental with Driver",
    service_excursion: "Excursions to any direction as per your request",
    service_tours: "Tours",
    learn_more: "Learn More <i class='fa-solid fa-chevron-right'></i>",
    car_list_title: "List of Cars We Offer",
    partners_title: "Our Partners",
    service_coverage: "We offer our services in every region of Azerbaijan.",
    comfort_reliability_title: "Comfort and Reliability",
    comfort_reliability_text:
      "With our services, you will experience maximum comfort during your journey. Easily book your car and be assured that it will be delivered on time.",
    customer_satisfaction_title: "Customer Satisfaction",
    customer_satisfaction_text:
      "Thanks to our rich experience in transportation, we have many satisfied customers and partners, which is the best indicator of our professional and quality services.",
    services_offered: "Services We Can Offer You",
    airport_transfer: "Airport Transfer",
    find_on_map: "Find Us on the Map",
    why_us: "Why Us?",
    professional_drivers: "Professional Drivers",
    professional_drivers_desc: "Our drivers are known for their professionalism and punctuality",
    safety: "Safety",
    safety_desc: "Our clients' safety is our top priority",
    reliable_guidance: "Reliable Guidance",
    reliable_guidance_desc: "You can rely on our knowledge and experience to guide you on your tour",
    premium_service: "Premium Service",
    premium_service_desc: "Premium quality and award-winning customer service",
    videos: "Videos",
    cars: "Cars",
    address: "Address",
    location: "Location",
    location_all: "All",
    location_baku: "Baku",
    location_ganja: "Ganja",
    location_sumgait: "Sumgait",
    location_mingecevir: "Mingechevir",
    location_lenkaran: "Lankaran",
    location_shirvan: "Shirvan",
    location_gabala: "Gabala",
    location_agdam: "Agdam",
    location_masalli: "Masalli",
    location_nakhchivan: "Nakhchivan",
    category: "Category",
    category_all: "All",
    category_option1: "Category 1",
    category_option2: "Category 2",
  },
  ru: {
    home: "Главная",
    about: "О нас",
    services: "Наши услуги",
    gallery: "Галерея",
    tours: "Туры",
    contact: "Контакт",
    language_az: "АЗ",
    language_ru: "РУ",
    language_en: "АН",
    currency_azn: "AZН",
    currency_usd: "USD",
    currency_eur: "ЕВР",
    slide1_title: "Ваш местный трансфер - начните комфортное и безопасное путешествие!",
    slide1_description:
      "Ваш местный трансфер - начните комфортное и безопасное путешествие! Легко планируйте городские и аэропортовые трансферы с LocalTransfer.com. Опытные водители и комфортабельные автомобили обеспечат вашу безопасность и комфорт. Заказывайте напрямую",
    slide2_title: "Ваш местный трансфер - начните комфортное и безопасное путешествие!",
    slide2_description:
      "Ваш местный трансфер - начните комфортное и безопасное путешествие! Легко планируйте городские и аэропортовые трансферы с LocalTransfer.com. Опытные водители и комфортабельные автомобили обеспечат вашу безопасность и комфорт. Заказывайте напрямую",
    slide3_title: "Ваш местный трансфер - начните комфортное и безопасное путешествие!",
    slide3_description:
      "Ваш местный трансфер - начните комфортное и безопасное путешествие! Легко планируйте городские и аэропортовые трансферы с LocalTransfer.com. Опытные водители и комфортабельные автомобили обеспечат вашу безопасность и комфорт. Заказывайте напрямую",
    step1_label: "Введите детали поездки",
    step2_label: "Выберите автомобиль",
    step3_label: "Введите контактную информацию",
    step4_label: "Просмотрите детали заказа",

    ride_details_title: "ДЕТАЛИ ПОЕЗДКИ",
    pickup_date_label: "Дата забора",
    pickup_time_label: "Время забора",
    route_label: "Маршрут",
    select_route: "Выберите маршрут",
    route_naxcivan: "Нахичевань",
    route_lenkeran: "Ленкорань",
    route_sirvan: "Ширван",
    route_qebele: "Габала",
    route_agdam: "Агдам",
    route_masalli: "Масаллы",
    transfer_type_label: "Тип трансфера",
    one_way_option: "В одну сторону",
    total_distance_label: "Общее расстояние",
    total_time_label: "Общее время",
    total_label: "Итог",
    vehicle_filter_title: "ФИЛЬТР АВТОМОБИЛЕЙ",
    passenger_label: "Пассажиры",
    bag_label: "Чемоданы",
    standard_label: "Стандарт",
    type_label: "Тип",
    select_option: "Выбрать",
    all_vehicles: "Все автомобили",
    minivan: "Минивэн",
    contact_info_title: "Контактная информация",
    name_label: "Имя",
    surname_label: "Фамилия",
    email_label: "Эл. адрес",
    phone_label: "Телефон",
    order_note_label: "Дополнительные примечания к заказу",
    ride_details: "Детали поездки",
    order_title: "Заказ",
    payment_method_label: "Способ оплаты:",
    payment_method_value: "Наличные при доставке",
    privacy_note:
      "Ваши личные данные будут использованы для обработки вашего заказа, поддержки вашего опыта на этом сайте и для других целей, описанных в нашей политике конфиденциальности.",
    confirm_order_button: "Подтвердить заказ",
    step_0_button_next: "Выберите транспорт <i class='fa-solid fa-chevron-right'></i>",
    step_1_button_prev: "<i class='fa-solid fa-chevron-left'></i> Выберите детали поездки",
    step_1_button_next: "Введите контактные данные <i class='fa-solid fa-chevron-right'></i>",
    step_2_button_prev: "<i class='fa-solid fa-chevron-left'></i> Выберите транспорт",
    step_2_button_next: "Просмотрите детали заказа <i class='fa-solid fa-chevron-right'></i>",
    step_3_button_prev: "<i class='fa-solid fa-chevron-left'></i> Введите контактные данные",
    step_3_button_next: "Забронировать сейчас <i class='fa-solid fa-chevron-right'></i>",
    intro_heading:
      "LocalTransfer.com создан для упрощения процесса путешествий, предлагая удобные и надежные транспортные решения.",
    intro_description:
      "С нашими профессиональными водителями и большим автопарком мы предлагаем качественное обслуживание и индивидуальные маршруты. Путешествуйте с нами, чтобы открыть для себя красоту Азербайджана!",
    service_airport: "Трансферы из аэропорта",
    service_vip: "VIP-трансферы",
    service_rental: "Аренда автомобиля с водителем",
    service_excursion: "Экскурсии по любому направлению на ваш выбор",
    service_tours: "Туры",
    learn_more: "Узнать больше <i class='fa-solid fa-chevron-right'></i>",
    car_list_title: "Список предлагаемых автомобилей",
    partners_title: "Наши партнеры",
    service_coverage: "Мы предлагаем наши услуги в каждом регионе Азербайджана.",
    comfort_reliability_title: "Комфорт и надежность",
    comfort_reliability_text:
      "Благодаря нашим услугам вы получите максимальный комфорт во время поездки. Легко бронируйте автомобиль и будьте уверены, что получите его вовремя.",
    customer_satisfaction_title: "Удовлетворенность клиентов",
    customer_satisfaction_text:
      "Благодаря нашему богатому опыту в сфере транспорта, у нас много довольных клиентов и партнеров, что является лучшим показателем надежности наших профессиональных и качественных услуг.",
    services_offered: "Услуги, которые мы можем вам предложить",
    airport_transfer: "Трансфер в аэропорт",
    find_on_map: "Найдите нас на карте",
    why_us: "Почему мы?",
    professional_drivers: "Профессиональные водители",
    professional_drivers_desc: "Наши водители известны своим профессионализмом и пунктуальностью",
    safety: "Безопасность",
    safety_desc: "Безопасность наших клиентов - наш главный приоритет",
    reliable_guidance: "Надежное руководство",
    reliable_guidance_desc: "Вы можете положиться на наши знания и опыт, чтобы сопровождать вас в туре",
    premium_service: "Премиум-услуги",
    premium_service_desc: "Премиальное качество и отмеченное наградами обслуживание клиентов",
    videos: "Видео",
    cars: "Автомобили",
    address: "Адрес",
    location: "Местоположение",
    location_all: "Все",
    location_baku: "Баку",
    location_ganja: "Гянджа",
    location_sumgait: "Сумгаит",
    location_mingecevir: "Мингечаур",
    location_lenkaran: "Ленкорань",
    location_shirvan: "Ширван",
    location_gabala: "Габала",
    location_agdam: "Агдам",
    location_masalli: "Масаллы",
    location_nakhchivan: "Нахичевань",
    category: "Категория",
    category_all: "Все",
    category_option1: "Категория 1",
    category_option2: "Категория 2",
  },
};

function changeLanguage(language) {
  localStorage.setItem("selectedLanguage", language);

  document.querySelectorAll("[data-key]").forEach((element) => {
    const key = element.getAttribute("data-key");
    element.innerHTML = translations[language][key];
  });

  // Dil seçimi göstermek için `x-text` güncelleniyor.
  document.querySelectorAll("[x-text]").forEach((element) => {
    const selectedLang = localStorage.getItem("selectedLanguage") || "AZ";
    if (element.getAttribute("x-text") === "selected === '' ? 'AZ' : selected") {
      element.textContent = selectedLang.toUpperCase();
    }
  });
}

document.addEventListener("DOMContentLoaded", function () {
  const selectedLanguage = localStorage.getItem("selectedLanguage") || "az";

  document.querySelectorAll("[data-key]").forEach((element) => {
    const key = element.getAttribute("data-key");
    element.innerHTML = translations[selectedLanguage][key];
  });

  document.querySelectorAll("[x-text]").forEach((element) => {
    const selectedLang = localStorage.getItem("selectedLanguage") || "AZ";
    if (element.getAttribute("x-text") === "selected === '' ? 'AZ' : selected") {
      element.textContent = selectedLang.toUpperCase();
    }
  });
});
